### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [jobcurtis/upton-sinclair_oil#1]
- [x] Sinclair should have a se:name.person.full-name entry in the metadata for his full name (see his Wiki entry).
- [x] The PGDP Canada team should have a se:url.homepage entry in the metadata.
- [x] Since Sinclair wrote the preface, a separate writer-of-preface entry isn't necessary, you can just add the "wpr" role to the author entry.
- [x] The Spanish phrases are proper names, so aren't italicized; see SEMoS [8.2.9.2](https://standardebooks.org/manual/1.7.0/single-page#8.2.9.2). Ditto L'Etoile. 
- [x] Conversely, "Vae victis" is Latin and so should be tagged.
- [x] Since the painter doesn't have a Wiki link, his name should be wrapped in a `<b epub:type="z3998:personal-name">` in the colophon; see [SEMoS 6.6.4.2](https://standardebooks.org/manual/1.7.0/single-page#6.6.4.2).
- [x] Only periods and commas go inside quotes (we make an exception for semi-colons in dialog); e.g. the semi-colon in 'whites;' in ch. 11, e.g., should be outside the quote, while the "…because you always kid me;" in ch. 8 stays in because it's dialog. There are a few other non-dialog ones to be fixed. (The "your old Paul;" in ch. 7 isn't dialog because it isn't being said directly.) Since this is changing content, it would be Editorial.
- [x] The names of newspapers, e.g. Angel City Evening Howler, should be italicized and semanticated, not quoted; see [SEMoS 8.2.11](https://standardebooks.org/manual/1.7.0/single-page#8.2.11).
- [x] Ditto book names, e.g. "The Ladies' Guide…" (at least it sounds like a book name?) and Arabian Nights. And ship names, e.g. "Siren". And films, e.g. "Hearts of Steel". Anything on that list. (There are a _lot_ of movie titles, so a thorough search will be needed.)
- [x] The blockquote in chapter 9 is not a complete poem, so it's type should be verse; see [SEMoS 7.5.6.1](https://standardebooks.org/manual/1.7.0/single-page#7.5.6.1).
- [x] Sounds like Whanhnh, ump-um, puff-puff, etc. are italicized; see [SEMoS 8.2.6](https://standardebooks.org/manual/1.7.0/single-page#8.2.6).
- [x] I believe the "phosidae" in ch. 13 should be tagged as taxonomy; see SEMoS [8.2.12](https://standardebooks.org/manual/1.7.0/single-page#8.2.12).
- [x] Long speeches like the one in ch. 5 (—for the days of your trials…) should be in a blockquote. Ditto the long quote of the index card in ch. 10 and the letter in ch. 13, etc.
- [x] There should be a NBSP between the feet and inches in the height in that card; see SEMoS [8.8.7.2](https://standardebooks.org/manual/1.7.0/single-page#8.8.7.2).
- [x] Numbers longer than three digits, e.g. 2300, 2437 in ch. 6, should have comma separators; see SEMoS [8.8.4](https://standardebooks.org/manual/1.7.0/single-page#8.8.4). Mathematical numbers only, not years, addresses, etc.
- [x] The "Oi!…" in ch. 14 is explicitly stated as being Yiddish, and is not in M-W, so should be tagged accordingly.
- [x] We almost never use all caps, so the SPOOKS should be in titlecase and formatted as `<strong>`; see [SEMoS 8.3.3](https://standardebooks.org/manual/1.7.0/single-page#8.3.3). (The radio call letters are a new one for me, I'll have to ask Alex about them.)
- [x] The headline CSS can be simplified, I think. Since the only thing in the blockquotes are `<p>`s, then the center can be on the p as well, and if the default is italic, then only one extra element is needed to small-cap the first line. (And just as a note, Alex normally is not crazy about classes, but there are enough headlines in enough different chapters here that I think it's warranted; we'll see if he disagrees.)
````
.headline > p{
	text-align: center;
	text-indent: 0;
	font-style: italic;
}

.headline > p:first-of-type{
	font-style: normal;
	font-variant: small-caps;
}
````

**Comment by jobcurtis** [comment]
Thanks for your review. Working on those items now. Regarding 'vae victis', I left that alone as it can be found in [Merriam Webster](https://www.merriam-webster.com/dictionary/vae%20victis). Should I still italicise/tag it?

Is removing quotation marks and replacing them with italics an editorial change?

**Comment by vr8hub** [comment]
It’s in MW, but as a “Latin phrase,” so we tag it. When it tells us it’s a non-English phrase (Latin, French, etc.), then we believe it. :)

I don’t usually mark it so, but if you do them in their own commit, it’s easy to change if Alex feels differently.

**Comment by jobcurtis** [comment]
Gotcha. Another question; generally Sinclair quotes the name of the newspaper, but not the name of its hometown. For example, 
```
The Roseville “Eagle”⁠—that was the name of the paper⁠—was boastful of Eli[...]
```
In this case would you italicise the whole thing, or just the part that Sinclair quoted? He's not even entirely consistent about this, sometimes we get `The Angel City "Evening Howler"`, but there's one or two instances of `The "Angel City Evening Howler"`.

**Comment by jobcurtis** [comment]
Also, regarding the letter in chapter 13, how do you handle blockquotes that contain asides from the author? Should the letter be split into two separate blockquotes, and if so what happens to the dash? For reference:
```
Bunny received a letter from Rachel. “Dear <abbr>Mr.</abbr> Ross”⁠—she always addressed
him that way, alone of his classmates; it was her way of maintaining her proletarian dignity,
in dealing with a person of great social pretensions. “We are home after picking all 
the prunes in California[...]
```

**Comment by jobcurtis** [comment]
Alright I think I've resolved all those issues except the blockquote around the letter. For the newspapers, where Sinclair used quotes I have italicised those parts. If that's wrong I can change it fairly easily.

**Comment by vr8hub** [comment]
Re the newspapers, you did what I do. I see this all the time, references to _The New York Times_, the _New York Times_, and the New York _Times_. I tag whatever they're referencing; if they're not trying to be consistent, I don't see any reason to impose it. (And I'm not sure the "right" way to be consistent, anyway.)

Re the letter, in this case I would just tag the salutation but leave it in the paragraph, and then make the blockquote start with the actual text of the letter "We are home…". IOW, 
````
Bunny received … great social pretensions.

    "We are home after… to meet you."

Bunny replied…
````

**Comment by jobcurtis** [comment]
Alright, I've done that as well. I think this is ready for you again.

**Comment by vr8hub** [comment]
Just a few nits that I don't think are worth opening another issue for.
- [x] The full-name attribute should directly follow the file-as attribute. (See the order of attributes in SEMoS 9.11).
(Without looking I would have told you the homepage should precede the role, but since it follows it in the manual, we're going to leave it.)
- [x] Modernize spelling modernizes Cañon to Canyon, and should be accepted.
- [x] Semanticate wants to add an "eoc" class to the S.P.U. in one of the headlines. I'm honestly not sure if that's correct or not (it doesn't _feel_ right, since it's a headline), so I'm fine with leaving it and letting Alex decide when he publishes it.
- [x] The ToC needs to be regenerated, since of the chapter headers was changed to add the "boat" semantic.
- [x] Speaking of which, the _Bennington_, being a "transport with 2K troops," definitely qualifies as a "ship," not a "boat." I'm not sure whether the "floating mansion" (Siren) and the yacht Conqueror should be ships or boats. I've actually asked about this before, and there isn't a clear distinction, so we can leave them boats and Alex can change them if he prefers.
- [x] You added the salutation tag, but not the corresponding CSS (see SEMoS [7.7.3.5.1](https://standardebooks.org/manual/1.7.0/single-page#7.7.3.5.1); only the salutation CSS is needed.
- [x] There's are "Honks" in 3.1 that I think qualify as sounds?
- [x] We keep our CSS in alpha sorted order, so the "song" line should go before the "verse" lines in those elements. (I'm just the messenger. :)
- [x] The film _The Golden Couch_ is properly tagged but still in quotes in 18.1; the quotes aren't needed since it's italicized.

**Comment by jobcurtis** [comment]
A couple of questions about those points;

>Modernize spelling modernizes Cañon to Canyon, and should be accepted.

I originally reverted this because Cañon is the correct spelling in spanish, and it's explicitly about the character reading signs written in spanish. Should I still modernise this to the english spelling?

>You added the salutation tag, but not the corresponding CSS (see SEMoS [7.7.3.5.1](https://standardebooks.org/manual/1.7.0/single-page#7.7.3.5.1); only the salutation CSS is needed.

Here do you mean the css rule applying `font-style: small-caps`? I think the `text-indent` one wouldn't apply anyway as the salutation is in a `span`, not a `p`. If we want small caps, would it be better to use a `b` element than to add a css rule, as suggested in [7.7.2.6](https://standardebooks.org/manual/1.7.0/single-page#7.7.2.6)?

I've just pushed fixes for the rest of your points.

Also, a question about this snippet;

```html
<i xml:lang="fr">Schmolsky-Superba Présente l’Etoile Américaine, Viola Tracy, dans La Couche d’Or, Cinéma-Mélodrame de la Société en Huit Reels.</i>
```

Here, I think 'La Couche d’Or' should be tagged as `epub:type="se:name.visual-art.film"`. Since it would normally be italicised, but the quote is already in italics, should it therefore be set in roman font? If so, would this css be the correct way to achieve that?

```css
i > [epub|type~="se:name.visual-art.film"]{
	font-style: normal;
}
```

**Comment by vr8hub** [comment]
1. Good point, yes, I agree.
2. Yes, honestly I forgot about that, because I always have our standard letter CSS if I have letters.
3. Yes and yes. Good catch!

**Comment by jobcurtis** [comment]
Great, I have just pushed those few changes.
